# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/tgpu-gen"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/tgpu-jit"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/tgpu-wgsl-parser"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/tinyest"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/tinyest-for-wgsl"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/typegpu"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/unplugin-typegpu"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/apps/typegpu-docs"
    schedule:
      interval: "weekly"
