packages:
  - packages/*
  - apps/*

catalog:
  arktype: 2.1.22

catalogs:
  build:
    jiti: ^2.6.0
    tsup: ^8.5.0
    unbuild: ^3.5.0
  example:
    wgpu-matrix: ^3.4.0
  frontend:
    fuse.js: ^7.1.0
    vite-imagetools: ^9.0.0
  test:
    vitest: ^3.2.4
  types:
    '@webgpu/types': ^0.1.65
    typescript: ^5.8.2
