packages:
  - packages/*
  - apps/*

catalog:
  '@babel/types': ^7.29.0
  arktype: ^2.1.22

catalogs:
  build:
    jiti: ^2.6.0
    rollup: ^4.60.0
    tsdown: ^0.21.4
    unbuild: ^3.5.0
  example:
    three: ^0.181.0
    wgpu-matrix: ^3.4.0
  frontend:
    fuse.js: ^7.1.0
    vite-imagetools: ^9.0.0
  test:
    vitest: ^4.1.2
  types:
    '@types/three': ^0.181.0
    '@webgpu/types': ^0.1.66
    '@types/node': ^24.1.0
    typescript: npm:tsover@^5.9.11
