packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  arktype: ^2.1.22

catalogs:
  build:
    tsup: ^8.5.0
    unbuild: ^3.5.0
    jiti: ^2.6.0
  types:
    typescript: ^5.9.3
    '@webgpu/types': ^0.1.66
  test:
    vitest: ^3.2.4
  frontend:
    'vite-imagetools': ^9.0.0
    'fuse.js': ^7.1.0
  example:
    'wgpu-matrix': ^3.4.0
