// oxlint-disable typescript/no-unnecessary-type-assertion -- import.meta.glob is inferred incorrectly by oxlint
import pathe from 'pathe';
import * as R from 'remeda';
import type {
  Example,
  ExampleCommonFile,
  ExampleMetadata,
  ExampleSource,
  ExampleSrcFile,
  PendingExampleSrcFile,
  ThumbnailPair,
} from '../utils/examples/types.ts';
import { atom } from 'jotai';

function extractUrlFromViteImport(importFn: () => void): [URL | undefined, boolean] {
  const filePath = String(importFn);
  const match = filePath.match(/\(\)\s*=>\s*import\(["`']([^"`']+)["`']\)/);

  if (match?.[1]) {
    const isRelative = match[1].startsWith('./');
    return [new URL(match[1], window.location.origin), isRelative];
  }

  return [undefined, false];
}

function noCacheImport<T>(importFn: () => Promise<T>): Promise<T> {
  const [url, isRelative] = extractUrlFromViteImport(importFn);

  if (!url) {
    throw new Error(`Could not no-cache-import using ${importFn}`);
  }

  url.searchParams.append('update', Date.now().toString());
  return import(/* @vite-ignore */ `${isRelative ? '.' : ''}${url.pathname}${url.search}`);
}

function pathToExampleKey(path: string): string {
  return R.pipe(
    path,
    (p) => pathe.relative('./', p), // removing parent folder
    (p) => p.split('/'), // splitting into segments
    ([category, name]) => `${category}--${name}`,
  );
}

function pathToRelativePath(path: string): string {
  const pathRelToExamples = pathe.relative('./', path);
  const categoryDir = pathRelToExamples.split('/')[0];
  const exampleDir = pathRelToExamples.split('/')[1];
  const examplePath = pathe.join(categoryDir, exampleDir);

  return pathe.relative(examplePath, path);
}

function withCoolFactorFallback(metadata: ExampleMetadata): ExampleMetadata {
  return Number.isFinite(metadata.coolFactor) ? metadata : { ...metadata, coolFactor: 0 };
}

const metaFiles = R.pipe(
  import.meta.glob('./**/meta.json', {
    eager: true,
    import: 'default',
  }) as Record<string, ExampleMetadata>,
  R.mapKeys(pathToExampleKey),
  R.mapValues(withCoolFactorFallback),
);

// Files that were generated by stripping away use of overloaded operators in .ts files
// './<category>/<example>/[<subdir>/]<file>.tsnotover.tsx?'
const exampleTsnotoverFiles = import.meta.glob(
  ['./*/**/*.tsnotover.ts', './*/**/*.tsnotover.tsx'],
  {
    query: 'raw',
    import: 'default',
  },
) as Record<string, () => Promise<string>>;

function replaceExt(key: string, newExt: string) {
  return `${key.substring(0, key.length - pathe.extname(key).length)}${newExt}`;
}

const exampleTsFiles = R.pipe(
  // './<category>/<example>/[<subdir>/]<file>.tsx?'
  import.meta.glob(['./*/**/*.ts', './*/**/*.tsx'], {
    query: 'raw',
    import: 'default',
  }) as Record<string, () => Promise<string>>,
  R.entries(),
  R.filter(([key]) => !key.includes('.tsnotover.')),
  R.map(
    ([key, getContent]): PendingExampleSrcFile => ({
      exampleKey: pathToExampleKey(key),
      path: pathToRelativePath(key),
      getContent,
      getTsnotoverContent:
        exampleTsnotoverFiles[replaceExt(key, `.tsnotover${pathe.extname(key)}`)],
    }),
  ),
  R.groupBy(R.prop('exampleKey')),
);

const tsFilesImportFunctions = R.pipe(
  import.meta.glob(['./*/*/index.ts', './*/*/index.tsx']) as Record<string, () => Promise<unknown>>,
  R.mapKeys(pathToExampleKey),
);

const htmlFiles = R.pipe(
  import.meta.glob('./**/index.html', {
    query: 'raw',
    import: 'default',
  }) as Record<string, () => Promise<string>>,
  R.entries(),
  R.map(
    ([key, getContent]): PendingExampleSrcFile => ({
      exampleKey: pathToExampleKey(key),
      path: pathToRelativePath(key),
      getContent,
    }),
  ),
  R.groupBy(R.prop('exampleKey')),
);

const thumbnailFiles = R.pipe(
  import.meta.glob('./**/thumbnail.png', {
    eager: true,
    import: 'default',
    query: 'w=512;1024',
  }) as Record<string, string | [string, string]>,
  R.mapKeys(pathToExampleKey),
  R.mapValues((value, key): ThumbnailPair => {
    if (typeof value === 'string') {
      throw new Error(
        `Thumbnail for example "${key}" is too small (required width is at least 513 pixels).`,
      );
    }
    return { small: value[0], large: value[1] };
  }),
);

const API_RULES: { id: string; pattern: RegExp }[] = [
  { id: 'compute', pattern: /\.(computeFn|createComputePipeline|createGuardedComputePipeline)/ },
  { id: 'textures', pattern: /d\.texture/ },
  { id: 'storage textures', pattern: /d\.textureStorage|storageTexture:/ },
  { id: 'samplers', pattern: /createSampler|d\.sampler/ },
  { id: 'atomics', pattern: /d\.atomic/ },
  { id: 'vertex layouts', pattern: /tgpu\.vertexLayout/ },
  { id: 'bind group layouts', pattern: /tgpu\.bindGroupLayout/ },
  { id: 'storage buffers', pattern: /\$usage\([\s\S]*?'storage'/ },
  { id: 'index buffers', pattern: /withIndexBuffer|setIndexBuffer|\$usage\('index'/ },
  {
    id: 'instancing',
    pattern: /instanceCount|drawInstanced|builtin\.instanceIndex|vertexLayout[^\n]*'instance'/,
  },
  { id: 'bindless buffers', pattern: /\.createUniform|\.createReadonly|\.createMutable/ },
  { id: 'subgroups', pattern: /subgroups/ },
  { id: 'timestamp query', pattern: /timestamp-query/ },
  { id: 'external texture', pattern: /importExternalTexture|externalTexture/ },
  { id: 'stencil', pattern: /stencilFront|stencilBack/ },
  { id: 'unwrap', pattern: /\.unwrap\(/ },
  { id: 'raw shaders', pattern: /rawCodeSnippet/ },
  { id: 'three.js', pattern: /from ['"]three['"/]/ },
  { id: '~unstable', pattern: /\['~unstable'\]/ },
  { id: '@typegpu/noise', pattern: /@typegpu\/noise/ },
  { id: '@typegpu/sdf', pattern: /@typegpu\/sdf/ },
  { id: '@typegpu/color', pattern: /@typegpu\/color/ },
  { id: '@typegpu/react', pattern: /@typegpu\/react/ },
  { id: 'wgpu-matrix', pattern: /wgpu-matrix/ },
];

// TODO: Detect used APIs using `unplugin-macros`
// function detectUsedApis(_tsFiles: ExampleSrcFile[]): string[] {
//   const allContent = tsFiles.map((f) => f.content).join('\n');
//   return API_RULES.filter((r) => r.pattern.test(allContent)).map((r) => r.id);
// }

async function resolveExampleSrcFile(pending: PendingExampleSrcFile): Promise<ExampleSrcFile> {
  const [content, tsnotoverContent] = await Promise.all([
    pending.getContent(),
    pending.getTsnotoverContent?.(),
  ]);

  return {
    exampleKey: pending.exampleKey,
    path: pending.path,
    content,
    tsnotoverContent,
  };
}

export const examples = R.pipe(
  metaFiles,
  R.mapValues(
    (value, key) =>
      ({
        key,
        metadata: value,
        sourceAtom: atom(async (): Promise<ExampleSource> => {
          const [tsFiles, htmlFile] = await Promise.all([
            Promise.all(exampleTsFiles[key].map(resolveExampleSrcFile)),
            resolveExampleSrcFile(htmlFiles[key]?.[0]),
          ]);

          return {
            tsFiles,
            htmlFile,
          };
        }),
        tsImport: () => noCacheImport(tsFilesImportFunctions[key]),
        thumbnails: thumbnailFiles[key],
        usedApis: API_RULES.map((r) => r.id),
      }) satisfies Example,
  ),
);

export const examplesByCategory = R.groupBy(
  Object.values(examples),
  (example) => example.metadata.category,
);

export const common = R.pipe(
  import.meta.glob('./common/*.ts', {
    query: 'raw',
    eager: true,
    import: 'default',
  }) as Record<string, string>,
  R.mapValues(
    (content: string, key: string): ExampleCommonFile => ({
      common: true,
      path: pathe.basename(key),
      content,
    }),
  ),
  R.values(),
);

export const PLAYGROUND_KEY = 'playground__';
