import type { ExampleMetadata } from '../utils/examples/types.ts';

// './<category>/<example>/[<subdir>/]<file>.tsx?'
export const tsContentLazy = import.meta.glob<string>(['./*/**/*.ts', './*/**/*.tsx'], {
  query: 'raw',
  import: 'default',
});

// Files that were generated by stripping away use of overloaded operators in .ts files
// './<category>/<example>/[<subdir>/]<file>.tsnotover.tsx?'
export const tsnotoverContentLazy = import.meta.glob<string>(
  ['./*/**/*.tsnotover.ts', './*/**/*.tsnotover.tsx'],
  {
    query: 'raw',
    import: 'default',
  },
);

export const metaContent = import.meta.glob<ExampleMetadata>('./**/meta.json', {
  eager: true,
  import: 'default',
});
