import type { ExampleMetadata } from '../utils/examples/types.ts';

// './<category>/<example>/[<subdir>/]<file>.tsx?'
export const tsContentLazy = import.meta.glob(['./*/**/*.ts', './*/**/*.tsx'], {
  query: 'raw',
  import: 'default',
}) as Record<string, () => Promise<string>>;

// Files that were generated by stripping away use of overloaded operators in .ts files
// './<category>/<example>/[<subdir>/]<file>.tsnotover.tsx?'
export const tsnotoverContentLazy = import.meta.glob(
  ['./*/**/*.tsnotover.ts', './*/**/*.tsnotover.tsx'],
  {
    query: 'raw',
    import: 'default',
  },
) as Record<string, () => Promise<string>>;

export const metaContent = import.meta.glob('./**/meta.json', {
  eager: true,
  import: 'default',
}) as Record<string, ExampleMetadata>;
