const ANIMATION_DURATION = 1500; // can be changed
const MAGIC_NUMBER = 0.443;
const INPUT_SCALE = 0.1; // can be changed
const USER_SCALE = INPUT_SCALE * 1.00001;
const TRIANGLES_PER_ROW = 6 * Math.ceil(MAGIC_NUMBER / USER_SCALE);
const ROWS = Math.ceil(TRIANGLES_PER_ROW / 2);
const STEP_ROTATION_ANGLE = 60;
const SCALE = 0.5;

const TRIANGLE_COUNT = TRIANGLES_PER_ROW * ROWS;

export {
  ANIMATION_DURATION,
  TRIANGLE_COUNT,
  STEP_ROTATION_ANGLE,
  SCALE,
  USER_SCALE,
  TRIANGLES_PER_ROW,
};
