import type { AnyFn } from '../core/function/fnTypes.ts';
import { f32 } from '../data/numeric.ts';
import {
  abs,
  acos,
  acosh,
  asin,
  asinh,
  atan,
  atan2,
  atanh,
  ceil,
  cos,
  cosh,
  countLeadingZeros,
  exp,
  floor,
  log,
  log2,
  max,
  min,
  pow,
  sign,
  sin,
  sinh,
  sqrt,
  tan,
  tanh,
  trunc,
} from '../std/numeric.ts';
import type { DualFn } from '../types.ts';

export const mathToStd: Record<string, DualFn<AnyFn> | undefined> = {
  // -- one to one Math to WGSL correlation --
  abs,
  acos,
  acosh,
  asin,
  asinh,
  atan,
  atan2,
  atanh,
  ceil,
  cos,
  cosh,
  exp,
  floor,
  fround: f32 as DualFn<AnyFn>,
  clz32: countLeadingZeros,
  trunc,
  log,
  log2,
  pow,
  sign,
  sin,
  sinh,
  sqrt,
  tan,
  tanh,
  // -- varying in Math and two arg in WGSL, but we support varying in std --
  max,
  min,
  // -- possible if we extend std --
  cbrt: undefined,
  log10: undefined,
  log1p: undefined,
  f16round: undefined,
  hypot: undefined,
  expm1: undefined,
  // -- skipped --
  random: undefined,
  imul: undefined,
  round: undefined, // round(2.5) is 3 in JS and 2 in WGSL
} satisfies Partial<Record<keyof typeof Math, DualFn<AnyFn> | undefined>>;
